products = [
    {"id": 1, "name": "Laptop", "category": "electronics", "price": 55000, "stock": 12},
    {"id": 2, "name": "Phone", "category": "electronics", "price": 25000, "stock": 25},
    {"id": 3, "name": "Keyboard", "category": "accessories", "price": 1500, "stock": 40},
    {"id": 4, "name": "Mouse", "category": "accessories", "price": 800, "stock": 60},
    {"id": 5, "name": "Monitor", "category": "electronics", "price": 18000, "stock": 15},
    {"id": 6, "name": "Headphones", "category": "audio", "price": 3000, "stock": 30},
    {"id": 7, "name": "Speaker", "category": "audio", "price": 4500, "stock": 20},
    {"id": 8, "name": "Webcam", "category": "accessories", "price": 2500, "stock": 18},
    {"id": 9, "name": "Tablet", "category": "electronics", "price": 32000, "stock": 10},
    {"id": 10, "name": "Smartwatch", "category": "electronics", "price": 12000, "stock": 22},
    {"id": 11, "name": "Router", "category": "electronics", "price": 3200, "stock": 27},
    {"id": 12, "name": "External HDD", "category": "electronics", "price": 4200, "stock": 33},
    {"id": 13, "name": "USB Cable", "category": "accessories", "price": 300, "stock": 100},
    {"id": 14, "name": "Laptop Stand", "category": "accessories", "price": 1200, "stock": 35},
    {"id": 15, "name": "Mousepad", "category": "accessories", "price": 250, "stock": 80},
    {"id": 16, "name": "Charger", "category": "accessories", "price": 900, "stock": 55},
    {"id": 17, "name": "Bluetooth Earbuds", "category": "audio", "price": 3500, "stock": 28},
    {"id": 18, "name": "Soundbar", "category": "audio", "price": 8000, "stock": 14},
    {"id": 19, "name": "Microphone", "category": "audio", "price": 5500, "stock": 16},
    {"id": 20, "name": "Amplifier", "category": "audio", "price": 9500, "stock": 9},
    {"id": 21, "name": "Printer", "category": "electronics", "price": 9800, "stock": 11},
    {"id": 22, "name": "Scanner", "category": "electronics", "price": 7200, "stock": 8},
    {"id": 23, "name": "Graphic Tablet", "category": "electronics", "price": 14000, "stock": 13},
    {"id": 24, "name": "Gaming Chair", "category": "accessories", "price": 11000, "stock": 7},
    {"id": 25, "name": "Desk Lamp", "category": "accessories", "price": 700, "stock": 45},
    {"id": 26, "name": "Power Bank", "category": "accessories", "price": 1800, "stock": 38},
    {"id": 27, "name": "Wireless Mouse", "category": "accessories", "price": 1100, "stock": 42},
    {"id": 28, "name": "Earphones", "category": "audio", "price": 900, "stock": 65},
    {"id": 29, "name": "Turntable", "category": "audio", "price": 15500, "stock": 6},
    {"id": 30, "name": "Subwoofer", "category": "audio", "price": 6800, "stock": 12},
]
def Data():
    return products

